# .scrutinizer.yml
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
checks:
    php:
        code_rating: true
        duplication: false
filter:
    excluded_paths:
        - tests/*
        - vendor/*