# .scrutinizer.yml
tools:
    external_code_coverage:
        timeout: 600
checks:
    php:
        code_rating: true
        duplication: false
filter:
    excluded_paths:
        - tests/*
        - vendor/*
        - includes/plugin-activation.php