# .scrutinizer.yml
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
checks:
    php:
        code_rating: true
        duplication: false
filter:
    excluded_paths:
        - tests/*
        - vendor/*
tools:
    php_code_sniffer:
        config: { standard: WordPress }