language: php

sudo: false

php:
- 5.6
- 7.0
- 7.1

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.7 WP_MULTISITE=0

before_script:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
script:
- if [[ $TRAVIS_PHP_VERSION != '7.1'|| $WP_VERSION != 'latest'
  || $WP_MULTISITE != '0' ]]; then phpenv config-rm xdebug.ini; fi
- if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then phpunit --coverage-clover=coverage.clover --debug; else phpunit --debug; fi

after_script:
- if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
- if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover --access-token="4aa26d5b17f315b687b65085e10b9c1c049744c0eb23227f33f0e804283f5fe3";
  fi